version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  test-db:
    image: postgres:13
    volumes:
      - test_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - backend

  api:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    environment:
      DATABASE_URL: postgresql://postgres:password@db/api_development
      TEST_DATABASE_URL: postgresql://postgres:password@test-db/api_test
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test-db
    networks:
      - backend
      - frontend

  front:
    build: ./frontend
    volumes:
      - ./frontend:/front
      - node_modules:/front/node_modules
      - next:/front/.next
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    networks:
      - frontend

volumes:
  db:
  test_db:
  node_modules:
  next:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge